server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/person_bank
    username: bank
    password: Ly102030
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true